program: train.py
method: random
metric:
  goal: minimize
  name: min_val_loss_among_epochs
parameters:
  # See the description of the following hyperparameters here: 
  # https://github.com/lucamarini22/anomaly-marine-detection/blob/main/marineanomalydetection/parse_args_train.py 
  lr:
    values: [0.0002, 0.001, 0.01, 0.1] #[0.0002] #[0.0002, 0.001, 0.01] #, 0.1] #[2e-4]
  threshold:
    values: [0.6, 0.7, 0.8, 0.9] #[0.7, 0.8, 0.9, 0.95] #[0.9] #[0.1, 0.3, 0.9, 0.95]
  epochs:
    value: 900
  batch:
    values: [5, 10] #[5, 10]
  #seed:
  #  values: [73, 982] #[719]
  seed:
    min: 0
    max: 1000
  mu:
    values: [5, 9] #[5, 9]
  reduce_lr_on_plateau:
    values: [0, 1] #[0] #
  lambda_coeff:
    values: [1] #[0.25, 1] #[1] #
  #perc_labeled:
  #  values: [0.5] #[0.1, 0.2] # [0.5] #
