program: train.py
method: random
metric:
  goal: minimize
  name: min_val_loss_among_epochs
parameters:
  # See the description of the following hyperparameters here: 
  # https://github.com/lucamarini22/anomaly-marine-detection/blob/main/anomalymarinedetection/parse_args_train.py 
  lr:
    values: [0.0002, 0.001, 0.01] #, 0.1] #[2e-4]
  threshold:
    values: [0.9, 0.95]
  epochs:
    value: 900
  batch:
    values: [5, 10]
  seed:
    values: [719]
  mu:
    values: [5, 9]
  reduce_lr_on_plateau:
    values: [0, 1]
  lambda_coeff:
    values: [0.25]
