program: train.py
method: random
metric:
  goal: minimize
  name: min_val_loss_among_epochs
parameters:
  lr:
    values: [0.0002, 0.001, 0.01, 0.1]
  threshold:
    values: [0.6, 0.7, 0.8, 0.9]
  epochs:
    value: 2000
  batch:
    values: [5, 10] 
  seed:
    value: 
    #min: 0
    #max: 10000
  mu:
    values: [5, 9]
  
  
