program: train.py
method: random
metric:
  goal: minimize
  name: min_val_loss_among_epochs
parameters:
  lr: # Learning rate.
    values: [0.0002, 0.001, 0.01] #, 0.1] #[2e-4]
  threshold: # Confidence threshold for pseudo-labels.
    values: [0.9, 0.95]
  epochs: # Number of epochs to run.
    value: 900
  batch: # Batch size.
    values: [5, 10]
  seed:
    values: [719]
  mu: # Unlabeled data ratio.
    values: [5, 9]
  reduce_lr_on_plateau: # Reduces learning rate when no increase (0 or 1).
    values: [0, 1]
  lambda_coeff: # Coefficient of unlabeled loss.
    values: [0.25]
